import * as z from "zod";

// Copied from Tone.js
// https://github.com/Tonejs/Tone.js/blob/5d3485b5cf30439a07e06893a85e24874deae626/Tone/core/type/NoteUnits.ts
// Copied here so the WS server app doesn't have to import Tone.js just for this.
// prettier-ignore
type Note =
// {{{
    "Cbb-4" | "Cb-4" | "C-4" | "C#-4" | "Cx-4" | "Dbb-4" | "Db-4" | "D-4" | "D#-4" | "Dx-4" | "Ebb-4" | "Eb-4" | "E-4" | "E#-4" | "Ex-4" | "Fbb-4" | "Fb-4" | "F-4" | "F#-4" | "Fx-4" | "Gbb-4" | "Gb-4" | "G-4" | "G#-4" | "Gx-4" | "Abb-4" | "Ab-4" | "A-4" | "A#-4" | "Ax-4" | "Bbb-4" | "Bb-4" | "B-4" | "B#-4" | "Bx-4" |
    "Cbb-3" | "Cb-3" | "C-3" | "C#-3" | "Cx-3" | "Dbb-3" | "Db-3" | "D-3" | "D#-3" | "Dx-3" | "Ebb-3" | "Eb-3" | "E-3" | "E#-3" | "Ex-3" | "Fbb-3" | "Fb-3" | "F-3" | "F#-3" | "Fx-3" | "Gbb-3" | "Gb-3" | "G-3" | "G#-3" | "Gx-3" | "Abb-3" | "Ab-3" | "A-3" | "A#-3" | "Ax-3" | "Bbb-3" | "Bb-3" | "B-3" | "B#-3" | "Bx-3" |
    "Cbb-2" | "Cb-2" | "C-2" | "C#-2" | "Cx-2" | "Dbb-2" | "Db-2" | "D-2" | "D#-2" | "Dx-2" | "Ebb-2" | "Eb-2" | "E-2" | "E#-2" | "Ex-2" | "Fbb-2" | "Fb-2" | "F-2" | "F#-2" | "Fx-2" | "Gbb-2" | "Gb-2" | "G-2" | "G#-2" | "Gx-2" | "Abb-2" | "Ab-2" | "A-2" | "A#-2" | "Ax-2" | "Bbb-2" | "Bb-2" | "B-2" | "B#-2" | "Bx-2" |
    "Cbb-1" | "Cb-1" | "C-1" | "C#-1" | "Cx-1" | "Dbb-1" | "Db-1" | "D-1" | "D#-1" | "Dx-1" | "Ebb-1" | "Eb-1" | "E-1" | "E#-1" | "Ex-1" | "Fbb-1" | "Fb-1" | "F-1" | "F#-1" | "Fx-1" | "Gbb-1" | "Gb-1" | "G-1" | "G#-1" | "Gx-1" | "Abb-1" | "Ab-1" | "A-1" | "A#-1" | "Ax-1" | "Bbb-1" | "Bb-1" | "B-1" | "B#-1" | "Bx-1" |
    "Cbb0" | "Cb0" | "C0" | "C#0" | "Cx0" | "Dbb0" | "Db0" | "D0" | "D#0" | "Dx0" | "Ebb0" | "Eb0" | "E0" | "E#0" | "Ex0" | "Fbb0" | "Fb0" | "F0" | "F#0" | "Fx0" | "Gbb0" | "Gb0" | "G0" | "G#0" | "Gx0" | "Abb0" | "Ab0" | "A0" | "A#0" | "Ax0" | "Bbb0" | "Bb0" | "B0" | "B#0" | "Bx0" |
    "Cbb1" | "Cb1" | "C1" | "C#1" | "Cx1" | "Dbb1" | "Db1" | "D1" | "D#1" | "Dx1" | "Ebb1" | "Eb1" | "E1" | "E#1" | "Ex1" | "Fbb1" | "Fb1" | "F1" | "F#1" | "Fx1" | "Gbb1" | "Gb1" | "G1" | "G#1" | "Gx1" | "Abb1" | "Ab1" | "A1" | "A#1" | "Ax1" | "Bbb1" | "Bb1" | "B1" | "B#1" | "Bx1" |
    "Cbb2" | "Cb2" | "C2" | "C#2" | "Cx2" | "Dbb2" | "Db2" | "D2" | "D#2" | "Dx2" | "Ebb2" | "Eb2" | "E2" | "E#2" | "Ex2" | "Fbb2" | "Fb2" | "F2" | "F#2" | "Fx2" | "Gbb2" | "Gb2" | "G2" | "G#2" | "Gx2" | "Abb2" | "Ab2" | "A2" | "A#2" | "Ax2" | "Bbb2" | "Bb2" | "B2" | "B#2" | "Bx2" |
    "Cbb3" | "Cb3" | "C3" | "C#3" | "Cx3" | "Dbb3" | "Db3" | "D3" | "D#3" | "Dx3" | "Ebb3" | "Eb3" | "E3" | "E#3" | "Ex3" | "Fbb3" | "Fb3" | "F3" | "F#3" | "Fx3" | "Gbb3" | "Gb3" | "G3" | "G#3" | "Gx3" | "Abb3" | "Ab3" | "A3" | "A#3" | "Ax3" | "Bbb3" | "Bb3" | "B3" | "B#3" | "Bx3" |
    "Cbb4" | "Cb4" | "C4" | "C#4" | "Cx4" | "Dbb4" | "Db4" | "D4" | "D#4" | "Dx4" | "Ebb4" | "Eb4" | "E4" | "E#4" | "Ex4" | "Fbb4" | "Fb4" | "F4" | "F#4" | "Fx4" | "Gbb4" | "Gb4" | "G4" | "G#4" | "Gx4" | "Abb4" | "Ab4" | "A4" | "A#4" | "Ax4" | "Bbb4" | "Bb4" | "B4" | "B#4" | "Bx4" |
    "Cbb5" | "Cb5" | "C5" | "C#5" | "Cx5" | "Dbb5" | "Db5" | "D5" | "D#5" | "Dx5" | "Ebb5" | "Eb5" | "E5" | "E#5" | "Ex5" | "Fbb5" | "Fb5" | "F5" | "F#5" | "Fx5" | "Gbb5" | "Gb5" | "G5" | "G#5" | "Gx5" | "Abb5" | "Ab5" | "A5" | "A#5" | "Ax5" | "Bbb5" | "Bb5" | "B5" | "B#5" | "Bx5" |
    "Cbb6" | "Cb6" | "C6" | "C#6" | "Cx6" | "Dbb6" | "Db6" | "D6" | "D#6" | "Dx6" | "Ebb6" | "Eb6" | "E6" | "E#6" | "Ex6" | "Fbb6" | "Fb6" | "F6" | "F#6" | "Fx6" | "Gbb6" | "Gb6" | "G6" | "G#6" | "Gx6" | "Abb6" | "Ab6" | "A6" | "A#6" | "Ax6" | "Bbb6" | "Bb6" | "B6" | "B#6" | "Bx6" |
    "Cbb7" | "Cb7" | "C7" | "C#7" | "Cx7" | "Dbb7" | "Db7" | "D7" | "D#7" | "Dx7" | "Ebb7" | "Eb7" | "E7" | "E#7" | "Ex7" | "Fbb7" | "Fb7" | "F7" | "F#7" | "Fx7" | "Gbb7" | "Gb7" | "G7" | "G#7" | "Gx7" | "Abb7" | "Ab7" | "A7" | "A#7" | "Ax7" | "Bbb7" | "Bb7" | "B7" | "B#7" | "Bx7" |
    "Cbb8" | "Cb8" | "C8" | "C#8" | "Cx8" | "Dbb8" | "Db8" | "D8" | "D#8" | "Dx8" | "Ebb8" | "Eb8" | "E8" | "E#8" | "Ex8" | "Fbb8" | "Fb8" | "F8" | "F#8" | "Fx8" | "Gbb8" | "Gb8" | "G8" | "G#8" | "Gx8" | "Abb8" | "Ab8" | "A8" | "A#8" | "Ax8" | "Bbb8" | "Bb8" | "B8" | "B#8" | "Bx8" |
    "Cbb9" | "Cb9" | "C9" | "C#9" | "Cx9" | "Dbb9" | "Db9" | "D9" | "D#9" | "Dx9" | "Ebb9" | "Eb9" | "E9" | "E#9" | "Ex9" | "Fbb9" | "Fb9" | "F9" | "F#9" | "Fx9" | "Gbb9" | "Gb9" | "G9" | "G#9" | "Gx9" | "Abb9" | "Ab9" | "A9" | "A#9" | "Ax9" | "Bbb9" | "Bb9" | "B9" | "B#9" | "Bx9" |
    "Cbb10" | "Cb10" | "C10" | "C#10" | "Cx10" | "Dbb10" | "Db10" | "D10" | "D#10" | "Dx10" | "Ebb10" | "Eb10" | "E10" | "E#10" | "Ex10" | "Fbb10" | "Fb10" | "F10" | "F#10" | "Fx10" | "Gbb10" | "Gb10" | "G10" | "G#10" | "Gx10" | "Abb10" | "Ab10" | "A10" | "A#10" | "Ax10" | "Bbb10" | "Bb10" | "B10" | "B#10" | "Bx10" |
    "Cbb11" | "Cb11" | "C11" | "C#11" | "Cx11" | "Dbb11" | "Db11" | "D11" | "D#11" | "Dx11" | "Ebb11" | "Eb11" | "E11" | "E#11" | "Ex11" | "Fbb11" | "Fb11" | "F11" | "F#11" | "Fx11" | "Gbb11" | "Gb11" | "G11" | "G#11" | "Gx11" | "Abb11" | "Ab11" | "A11" | "A#11" | "Ax11" | "Bbb11" | "Bb11" | "B11" | "B#11" | "Bx11";
// }}}

// prettier-ignore
export const NoteSchema: z.ZodSchema<Note> =
// {{{
    z.union([
        z.literal("Cbb-4"), z.literal("Cb-4"), z.literal("C-4"), z.literal("C#-4"), z.literal("Cx-4"), z.literal("Dbb-4"), z.literal("Db-4"), z.literal("D-4"), z.literal("D#-4"), z.literal("Dx-4"), z.literal("Ebb-4"), z.literal("Eb-4"), z.literal("E-4"), z.literal("E#-4"), z.literal("Ex-4"), z.literal("Fbb-4"), z.literal("Fb-4"), z.literal("F-4"), z.literal("F#-4"), z.literal("Fx-4"), z.literal("Gbb-4"), z.literal("Gb-4"), z.literal("G-4"), z.literal("G#-4"), z.literal("Gx-4"), z.literal("Abb-4"), z.literal("Ab-4"), z.literal("A-4"), z.literal("A#-4"), z.literal("Ax-4"), z.literal("Bbb-4"), z.literal("Bb-4"), z.literal("B-4"), z.literal("B#-4"), z.literal("Bx-4"),
        z.literal("Cbb-3"), z.literal("Cb-3"), z.literal("C-3"), z.literal("C#-3"), z.literal("Cx-3"), z.literal("Dbb-3"), z.literal("Db-3"), z.literal("D-3"), z.literal("D#-3"), z.literal("Dx-3"), z.literal("Ebb-3"), z.literal("Eb-3"), z.literal("E-3"), z.literal("E#-3"), z.literal("Ex-3"), z.literal("Fbb-3"), z.literal("Fb-3"), z.literal("F-3"), z.literal("F#-3"), z.literal("Fx-3"), z.literal("Gbb-3"), z.literal("Gb-3"), z.literal("G-3"), z.literal("G#-3"), z.literal("Gx-3"), z.literal("Abb-3"), z.literal("Ab-3"), z.literal("A-3"), z.literal("A#-3"), z.literal("Ax-3"), z.literal("Bbb-3"), z.literal("Bb-3"), z.literal("B-3"), z.literal("B#-3"), z.literal("Bx-3"),
        z.literal("Cbb-2"), z.literal("Cb-2"), z.literal("C-2"), z.literal("C#-2"), z.literal("Cx-2"), z.literal("Dbb-2"), z.literal("Db-2"), z.literal("D-2"), z.literal("D#-2"), z.literal("Dx-2"), z.literal("Ebb-2"), z.literal("Eb-2"), z.literal("E-2"), z.literal("E#-2"), z.literal("Ex-2"), z.literal("Fbb-2"), z.literal("Fb-2"), z.literal("F-2"), z.literal("F#-2"), z.literal("Fx-2"), z.literal("Gbb-2"), z.literal("Gb-2"), z.literal("G-2"), z.literal("G#-2"), z.literal("Gx-2"), z.literal("Abb-2"), z.literal("Ab-2"), z.literal("A-2"), z.literal("A#-2"), z.literal("Ax-2"), z.literal("Bbb-2"), z.literal("Bb-2"), z.literal("B-2"), z.literal("B#-2"), z.literal("Bx-2"),
        z.literal("Cbb-1"), z.literal("Cb-1"), z.literal("C-1"), z.literal("C#-1"), z.literal("Cx-1"), z.literal("Dbb-1"), z.literal("Db-1"), z.literal("D-1"), z.literal("D#-1"), z.literal("Dx-1"), z.literal("Ebb-1"), z.literal("Eb-1"), z.literal("E-1"), z.literal("E#-1"), z.literal("Ex-1"), z.literal("Fbb-1"), z.literal("Fb-1"), z.literal("F-1"), z.literal("F#-1"), z.literal("Fx-1"), z.literal("Gbb-1"), z.literal("Gb-1"), z.literal("G-1"), z.literal("G#-1"), z.literal("Gx-1"), z.literal("Abb-1"), z.literal("Ab-1"), z.literal("A-1"), z.literal("A#-1"), z.literal("Ax-1"), z.literal("Bbb-1"), z.literal("Bb-1"), z.literal("B-1"), z.literal("B#-1"), z.literal("Bx-1"),
        z.literal("Cbb0"), z.literal("Cb0"), z.literal("C0"), z.literal("C#0"), z.literal("Cx0"), z.literal("Dbb0"), z.literal("Db0"), z.literal("D0"), z.literal("D#0"), z.literal("Dx0"), z.literal("Ebb0"), z.literal("Eb0"), z.literal("E0"), z.literal("E#0"), z.literal("Ex0"), z.literal("Fbb0"), z.literal("Fb0"), z.literal("F0"), z.literal("F#0"), z.literal("Fx0"), z.literal("Gbb0"), z.literal("Gb0"), z.literal("G0"), z.literal("G#0"), z.literal("Gx0"), z.literal("Abb0"), z.literal("Ab0"), z.literal("A0"), z.literal("A#0"), z.literal("Ax0"), z.literal("Bbb0"), z.literal("Bb0"), z.literal("B0"), z.literal("B#0"), z.literal("Bx0"),
        z.literal("Cbb1"), z.literal("Cb1"), z.literal("C1"), z.literal("C#1"), z.literal("Cx1"), z.literal("Dbb1"), z.literal("Db1"), z.literal("D1"), z.literal("D#1"), z.literal("Dx1"), z.literal("Ebb1"), z.literal("Eb1"), z.literal("E1"), z.literal("E#1"), z.literal("Ex1"), z.literal("Fbb1"), z.literal("Fb1"), z.literal("F1"), z.literal("F#1"), z.literal("Fx1"), z.literal("Gbb1"), z.literal("Gb1"), z.literal("G1"), z.literal("G#1"), z.literal("Gx1"), z.literal("Abb1"), z.literal("Ab1"), z.literal("A1"), z.literal("A#1"), z.literal("Ax1"), z.literal("Bbb1"), z.literal("Bb1"), z.literal("B1"), z.literal("B#1"), z.literal("Bx1"),
        z.literal("Cbb2"), z.literal("Cb2"), z.literal("C2"), z.literal("C#2"), z.literal("Cx2"), z.literal("Dbb2"), z.literal("Db2"), z.literal("D2"), z.literal("D#2"), z.literal("Dx2"), z.literal("Ebb2"), z.literal("Eb2"), z.literal("E2"), z.literal("E#2"), z.literal("Ex2"), z.literal("Fbb2"), z.literal("Fb2"), z.literal("F2"), z.literal("F#2"), z.literal("Fx2"), z.literal("Gbb2"), z.literal("Gb2"), z.literal("G2"), z.literal("G#2"), z.literal("Gx2"), z.literal("Abb2"), z.literal("Ab2"), z.literal("A2"), z.literal("A#2"), z.literal("Ax2"), z.literal("Bbb2"), z.literal("Bb2"), z.literal("B2"), z.literal("B#2"), z.literal("Bx2"),
        z.literal("Cbb3"), z.literal("Cb3"), z.literal("C3"), z.literal("C#3"), z.literal("Cx3"), z.literal("Dbb3"), z.literal("Db3"), z.literal("D3"), z.literal("D#3"), z.literal("Dx3"), z.literal("Ebb3"), z.literal("Eb3"), z.literal("E3"), z.literal("E#3"), z.literal("Ex3"), z.literal("Fbb3"), z.literal("Fb3"), z.literal("F3"), z.literal("F#3"), z.literal("Fx3"), z.literal("Gbb3"), z.literal("Gb3"), z.literal("G3"), z.literal("G#3"), z.literal("Gx3"), z.literal("Abb3"), z.literal("Ab3"), z.literal("A3"), z.literal("A#3"), z.literal("Ax3"), z.literal("Bbb3"), z.literal("Bb3"), z.literal("B3"), z.literal("B#3"), z.literal("Bx3"),
        z.literal("Cbb4"), z.literal("Cb4"), z.literal("C4"), z.literal("C#4"), z.literal("Cx4"), z.literal("Dbb4"), z.literal("Db4"), z.literal("D4"), z.literal("D#4"), z.literal("Dx4"), z.literal("Ebb4"), z.literal("Eb4"), z.literal("E4"), z.literal("E#4"), z.literal("Ex4"), z.literal("Fbb4"), z.literal("Fb4"), z.literal("F4"), z.literal("F#4"), z.literal("Fx4"), z.literal("Gbb4"), z.literal("Gb4"), z.literal("G4"), z.literal("G#4"), z.literal("Gx4"), z.literal("Abb4"), z.literal("Ab4"), z.literal("A4"), z.literal("A#4"), z.literal("Ax4"), z.literal("Bbb4"), z.literal("Bb4"), z.literal("B4"), z.literal("B#4"), z.literal("Bx4"),
        z.literal("Cbb5"), z.literal("Cb5"), z.literal("C5"), z.literal("C#5"), z.literal("Cx5"), z.literal("Dbb5"), z.literal("Db5"), z.literal("D5"), z.literal("D#5"), z.literal("Dx5"), z.literal("Ebb5"), z.literal("Eb5"), z.literal("E5"), z.literal("E#5"), z.literal("Ex5"), z.literal("Fbb5"), z.literal("Fb5"), z.literal("F5"), z.literal("F#5"), z.literal("Fx5"), z.literal("Gbb5"), z.literal("Gb5"), z.literal("G5"), z.literal("G#5"), z.literal("Gx5"), z.literal("Abb5"), z.literal("Ab5"), z.literal("A5"), z.literal("A#5"), z.literal("Ax5"), z.literal("Bbb5"), z.literal("Bb5"), z.literal("B5"), z.literal("B#5"), z.literal("Bx5"),
        z.literal("Cbb6"), z.literal("Cb6"), z.literal("C6"), z.literal("C#6"), z.literal("Cx6"), z.literal("Dbb6"), z.literal("Db6"), z.literal("D6"), z.literal("D#6"), z.literal("Dx6"), z.literal("Ebb6"), z.literal("Eb6"), z.literal("E6"), z.literal("E#6"), z.literal("Ex6"), z.literal("Fbb6"), z.literal("Fb6"), z.literal("F6"), z.literal("F#6"), z.literal("Fx6"), z.literal("Gbb6"), z.literal("Gb6"), z.literal("G6"), z.literal("G#6"), z.literal("Gx6"), z.literal("Abb6"), z.literal("Ab6"), z.literal("A6"), z.literal("A#6"), z.literal("Ax6"), z.literal("Bbb6"), z.literal("Bb6"), z.literal("B6"), z.literal("B#6"), z.literal("Bx6"),
        z.literal("Cbb7"), z.literal("Cb7"), z.literal("C7"), z.literal("C#7"), z.literal("Cx7"), z.literal("Dbb7"), z.literal("Db7"), z.literal("D7"), z.literal("D#7"), z.literal("Dx7"), z.literal("Ebb7"), z.literal("Eb7"), z.literal("E7"), z.literal("E#7"), z.literal("Ex7"), z.literal("Fbb7"), z.literal("Fb7"), z.literal("F7"), z.literal("F#7"), z.literal("Fx7"), z.literal("Gbb7"), z.literal("Gb7"), z.literal("G7"), z.literal("G#7"), z.literal("Gx7"), z.literal("Abb7"), z.literal("Ab7"), z.literal("A7"), z.literal("A#7"), z.literal("Ax7"), z.literal("Bbb7"), z.literal("Bb7"), z.literal("B7"), z.literal("B#7"), z.literal("Bx7"),
        z.literal("Cbb8"), z.literal("Cb8"), z.literal("C8"), z.literal("C#8"), z.literal("Cx8"), z.literal("Dbb8"), z.literal("Db8"), z.literal("D8"), z.literal("D#8"), z.literal("Dx8"), z.literal("Ebb8"), z.literal("Eb8"), z.literal("E8"), z.literal("E#8"), z.literal("Ex8"), z.literal("Fbb8"), z.literal("Fb8"), z.literal("F8"), z.literal("F#8"), z.literal("Fx8"), z.literal("Gbb8"), z.literal("Gb8"), z.literal("G8"), z.literal("G#8"), z.literal("Gx8"), z.literal("Abb8"), z.literal("Ab8"), z.literal("A8"), z.literal("A#8"), z.literal("Ax8"), z.literal("Bbb8"), z.literal("Bb8"), z.literal("B8"), z.literal("B#8"), z.literal("Bx8"),
        z.literal("Cbb9"), z.literal("Cb9"), z.literal("C9"), z.literal("C#9"), z.literal("Cx9"), z.literal("Dbb9"), z.literal("Db9"), z.literal("D9"), z.literal("D#9"), z.literal("Dx9"), z.literal("Ebb9"), z.literal("Eb9"), z.literal("E9"), z.literal("E#9"), z.literal("Ex9"), z.literal("Fbb9"), z.literal("Fb9"), z.literal("F9"), z.literal("F#9"), z.literal("Fx9"), z.literal("Gbb9"), z.literal("Gb9"), z.literal("G9"), z.literal("G#9"), z.literal("Gx9"), z.literal("Abb9"), z.literal("Ab9"), z.literal("A9"), z.literal("A#9"), z.literal("Ax9"), z.literal("Bbb9"), z.literal("Bb9"), z.literal("B9"), z.literal("B#9"), z.literal("Bx9"),
        z.literal("Cbb10"), z.literal("Cb10"), z.literal("C10"), z.literal("C#10"), z.literal("Cx10"), z.literal("Dbb10"), z.literal("Db10"), z.literal("D10"), z.literal("D#10"), z.literal("Dx10"), z.literal("Ebb10"), z.literal("Eb10"), z.literal("E10"), z.literal("E#10"), z.literal("Ex10"), z.literal("Fbb10"), z.literal("Fb10"), z.literal("F10"), z.literal("F#10"), z.literal("Fx10"), z.literal("Gbb10"), z.literal("Gb10"), z.literal("G10"), z.literal("G#10"), z.literal("Gx10"), z.literal("Abb10"), z.literal("Ab10"), z.literal("A10"), z.literal("A#10"), z.literal("Ax10"), z.literal("Bbb10"), z.literal("Bb10"), z.literal("B10"), z.literal("B#10"), z.literal("Bx10"),
        z.literal("Cbb11"), z.literal("Cb11"), z.literal("C11"), z.literal("C#11"), z.literal("Cx11"), z.literal("Dbb11"), z.literal("Db11"), z.literal("D11"), z.literal("D#11"), z.literal("Dx11"), z.literal("Ebb11"), z.literal("Eb11"), z.literal("E11"), z.literal("E#11"), z.literal("Ex11"), z.literal("Fbb11"), z.literal("Fb11"), z.literal("F11"), z.literal("F#11"), z.literal("Fx11"), z.literal("Gbb11"), z.literal("Gb11"), z.literal("G11"), z.literal("G#11"), z.literal("Gx11"), z.literal("Abb11"), z.literal("Ab11"), z.literal("A11"), z.literal("A#11"), z.literal("Ax11"), z.literal("Bbb11"), z.literal("Bb11"), z.literal("B11"), z.literal("B#11"), z.literal("Bx11"),
    ]);
// }}}

export default Note;
