name: deploy-ws

on:
  push:
    branches:
      - master

jobs:
  deploy-ws:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn run build:server
      - run: |
          mkdir dist
          cp -r server/dist/* dist/
          cp server/package.dist-ws.json dist/package.json
          cp yarn.lock dist/
          echo "web: yarn run start" > dist/Procfile
          git add dist --force
          git commit -m "Setup dist/ directory for WS deploy on Heroku"
      - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with:
          api_key: ${{ secrets.HEROKU_API_KEY }}
          email: ${{ secrets.HEROKU_EMAIL }}
          app_name: sync-tracker-ws
          heroku_branch: master
          subfolder: dist
